init: &init
  working_directory: ~/d8-pantheon
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    DEBUG: "true"
  docker:
    - image: docksal/bitbucket-pipelines-agent:edge-php


version: 2
jobs:
  build:
    <<: *init
    steps:
      - checkout

      - run:
          name: Set github token to avoid rate limit
          command: |
            composer config --global github-oauth.github.com $GIT_TOKEN
            git config --global user.email $GIT_EMAIL
            git config --global user.name $CIRCLE_USERNAME

      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.ssh
            - ~/.gitconfig

  code_sniffers:
    <<: *init

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: code-sniffers-cache

      - run:
          name: Install Coder Sniffer
          command: sh scripts/install_coder_sniffer.sh

      - run:
          name: Check custom code standard
          command: sh scripts/bin/phpcs.sh

      - save_cache:
          paths: ~/coder
          key: code-sniffers-cache

