init: &init
  working_directory: ~/d8-pantheon
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    DEBUG: "true"
  docker:
    - image: docksal/bitbucket-pipelines-agent:edge-php


version: 2
jobs:
  build:
    <<: *init
    steps:
      - checkout

      - restore_cache:
          key: terminus-cache

      - run:
          name: Set github token to avoid rate limit
          command: |
            composer config --global github-oauth.github.com $GIT_TOKEN
            git config --global user.email $GIT_EMAIL
            git config --global user.name $CIRCLE_USERNAME

      - run:
          name: Install Terminus
          command: sh scripts/bin/install_terminus.sh

      - save_cache:
          key: terminus-cache
          path: ~/terminus

      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.ssh
            - ~/.gitconfig

  code_sniffers:
    <<: *init

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: code-sniffers-cache

      - run:
          name: Install Coder Sniffer
          command: sh scripts/bin/install_coder_sniffer.sh

      - run:
          name: Check custom code standard
          command: scripts/bin/phpcs.sh

      - save_cache:
          paths: ~/coder
          key: code-sniffers-cache

  multidev:
    <<: *init
    steps:
      - restore_cache:
          keys: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo 'export PATH=$HOME/terminus/bin:$PATH' >> $BASH_ENV
      - run:
          name: Build environment for branch
          command: echo "Test build multidev"

  deploy_pantheon:
    <<: *init
    steps:
      - restore_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: echo "Test deploy to pantheon"

workflows:
  version: 2
  multi-build-flow:
    jobs:
      - code_sniffers
      - build:
          requires:
            - code_sniffers

      - multidev:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

      - deploy_pantheon:
          requires:
            - build
          filters:
            branches:
              only:
                - master
